version: "3.8"
services:
  grocy-mealie-sync:
    image: deejaydoubled/grocy2mealie-sync
    container_name: grocy-mealie-sync
    env_file: 
      - ./sync.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "main.py", "health"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s